# -*- coding: utf-8 -*-
"""Attack Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-klseWh1hOVjkXmZMP73FcSUnBCEzXKU
"""

import pandas as pd
import pickle

FILE_NAME = '/home/tom/Desktop/DNS_origional/dnsSummary_user'
FILE_NAME_EXTRACTED = '/home/tom/PycharmProjects/DNS_project/DNS_ip_port_extracted/dnsSummary_user'
FILE_EXTENSION = '.pcap.csv'
NUMBER_OF_USERS = 15


def extract_features():
    for i in range(1, NUMBER_OF_USERS + 1):
        user_data = pd.read_csv(FILE_NAME + str(i) + FILE_EXTENSION)
        user_data = user_data[['ip.dst', 'ip.src', 'udp.srcport','udp.dstport','dns.time']]
        user_data = user_data.dropna()
        user_data.to_csv(FILE_NAME_EXTRACTED + str(i) + FILE_EXTENSION)


def build_chunk_30_minutes(user_data):
    max_time = user_data['relative_time'].max()
    user_data_list = []
    i = 0
    while i < max_time:
        chunk = user_data.loc[(user_data['relative_time'] > i) & (user_data['relative_time'] < i + 1800)]
        chunk = chunk[['day', 'hour', 'dns_name']].values.tolist()
        if len(chunk) > 0:
            user_data_list.append(chunk)
        i += 1800
    return user_data_list


def build_users_chunks():
    all_users_chunks = []
    for i in range(1, NUMBER_OF_USERS+1):
        user_data = pd.read_csv(FILE_NAME_EXTRACTED + str(i) + FILE_EXTENSION)
        all_users_chunks.append(build_chunk_30_minutes(user_data))
    with open('../FileCenter/minimzed_data/all_user_chunks', 'wb') as fp:
        pickle.dump(all_users_chunks, fp)


if __name__ == '__main__':
    extract_features()

