# -*- coding: utf-8 -*-
"""Attack Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-klseWh1hOVjkXmZMP73FcSUnBCEzXKU
"""

import pandas as pd

FILE_NAME = '/content/drive/My Drive/DNS_project/DNS_origional/dnsSummary_user'
FILE_NAME_EXTRACTED = '/content/drive/My Drive/DNS__time_name_extracted/dnsSummary_user'
FILE_EXTENSION = '.pcap.csv'
NUMBER_OF_USERS = 15
DAYS = 7
HOURS = 24
EPOCH_DAY = 5


def extract_time(user_data):
    num_days = round(user_data['frame.time_epoch'] / 3600 / 24)
    day = (num_days + EPOCH_DAY) % DAYS + 1
    num_hours = round(user_data['frame.time_epoch'] / 3600)
    hour = num_hours % HOURS + 1
    new_user_data = pd.concat([day, hour, user_data['dns.qry.name']], axis=1)
    new_user_data.columns = ['day', 'hour', 'dns_name']
    return new_user_data


def build_users_data_structure():
    pass


def extract_features():
    for i in range(1, NUMBER_OF_USERS + 1):
        user_data = pd.read_csv(FILE_NAME + str(i) + FILE_EXTENSION)
        user_data = user_data.iloc[::2]
        user_data = user_data[['frame.time_epoch', 'dns.qry.name']]
        new_user_data = extract_time(user_data)
        new_user_data.to_csv(FILE_NAME_EXTRACTED + str(i) + FILE_EXTENSION)


if __name__ == '__main__':
    extract_features()
